#github账号登陆配置
github:
  client:
    id: 89cceb7e8f19ce08fdea
    secret: da8194efe08636b7adb017780b6fe7aee042b0ba
  redirect:
    uri: http://localhost:8080/callback

spring:
  datasource:
    url: jdbc:h2:~/community
    username: root
    password: h2
    driver-class-name: org.h2.Driver

  thymeleaf:
    cache: false

  #配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 2MB
      max-request-size: 20MB
logging:
  level:
    com.jiane.mapper.QuestionMapper: debug



mybatis:
  type-aliases-package: com.jiane.model
  mapper-locations: classpath:mapper/*Mapper.xml
