#github账号登陆配置
github:
  client:
    id: 89cceb7e8f19ce08fdea
    secret: da8194efe08636b7adb017780b6fe7aee042b0ba
  redirect:
    uri: http://121.41.17.80:8080/callback

spring:
  datasource:
    url: jdbc:mysql:121.41.17.80:3306/community
    username: root
    password: zhangMySql123
    driver-class-name: com.mysql.cj.jdbc.Driver

#  thymeleaf:
#    cache: false

  #配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
logging:
  level:
    root: info
    com.jiane.mapper: warn
  file:
    max-size: 50MB
    max-history: 30
    #配置每个日志文件最大的大小和历史日志存放时间
  path: logs/

mybatis:
  type-aliases-package: com.jiane.model
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 80
