#github账号登陆配置
github:
  client:
    id: 89cceb7e8f19ce08fdea
    secret: da8194efe08636b7adb017780b6fe7aee042b0ba
  redirect:
    uri: http://localhost:9090/callback
spring:
#    datasource:
#      url: jdbc:mysql://localhost:3306/community
#      username: root
#      password: mysql
#      driver-class-name: com.mysql.cj.jdbc.Driver
  datasource:
    username: root
    password: mysql #mysql8.0
    #    driver-class-name: com.alibaba.druid.proxy.DruidDriver #别用这个 用这个会报错
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    url: jdbc:mysql://localhost:3306/community?serverTimezone=Hongkong&useSSL=false&rewriteBatchedStatements=true&useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false

  #  thymeleaf:
  #    cache: false

  #配置文件上传大小限制
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 50MB
logging:
  level:
    root: debug
  #    com.jiane.mapper: warn
  file:
    max-size: 50MB
    max-history: 30
    #配置每个日志文件最大的大小和历史日志存放时间
  path: logs/

mybatis:
  type-aliases-package: com.jiane.model
  mapper-locations: classpath:mapper/*Mapper.xml
server:
  port: 9090


fdfs:
  connect-timeout: 600 #连接超时时间
  so-timeout: 1500 #读取时间
  pool:
    jmx-enabled: false
  thumb-image:
    height: 100
    width: 100
  tracker-list: 192.168.33.65:22122